import { useState } from "react";
import { BarChart3, Building2, DatabaseZap, Plus, ShieldCheck, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { AuthorityLayout } from "@/components/civic/AuthorityLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";

type Role = "citizen" | "authority" | "admin";
type AdminUser = { id: number; name: string | null; email: string | null; role: Role; departmentId: number | null };
type Department = { id: number; name: string; active: boolean };

export default function AdminManagement() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const users = trpc.civic.admin.users.useQuery(undefined, { enabled: user?.role === "admin" });
  const departments = trpc.civic.admin.departments.useQuery(undefined, { enabled: user?.role === "admin" });
  const categories = trpc.civic.admin.categories.useQuery(undefined, { enabled: user?.role === "admin" });
  const analytics = trpc.civic.authority.dashboard.useQuery(undefined, { enabled: user?.role === "admin" });
  const updateUser = trpc.civic.admin.updateUser.useMutation();
  const createDepartment = trpc.civic.admin.createDepartment.useMutation();
  const createCategory = trpc.civic.admin.createCategory.useMutation();
  const setDepartmentActive = trpc.civic.admin.setDepartmentActive.useMutation();
  const setCategoryActive = trpc.civic.admin.setCategoryActive.useMutation();
  const seedDemo = trpc.civic.admin.seedDemoData.useMutation();
  const [departmentName, setDepartmentName] = useState("");
  const [departmentDescription, setDepartmentDescription] = useState("");
  const [categoryName, setCategoryName] = useState("");
  const [categoryDepartment, setCategoryDepartment] = useState("");
  const refresh = () => Promise.all([utils.civic.admin.users.invalidate(), utils.civic.admin.departments.invalidate(), utils.civic.admin.categories.invalidate(), utils.civic.authority.dashboard.invalidate()]);

  if (user?.role !== "admin") return <AuthorityLayout><main className="grid min-h-screen place-items-center p-7"><section className="max-w-md rounded-3xl bg-white p-8 text-center shadow-sm"><ShieldCheck className="mx-auto h-10 w-10 text-rose-700" /><h1 className="mt-4 text-2xl font-black">Administrator access required</h1><p className="mt-2 text-slate-600">Only administrators can manage accounts, civic taxonomies, and system governance.</p></section></main></AuthorityLayout>;

  const saveUser = async (id: number, role: Role, departmentId: string) => {
    try { await updateUser.mutateAsync({ id, role, departmentId: role === "authority" && departmentId ? Number(departmentId) : null }); await refresh(); toast.success("User access updated."); }
    catch (error) { toast.error(error instanceof Error ? error.message : "User access could not be updated."); }
  };

  return <AuthorityLayout><main className="mx-auto max-w-7xl px-4 py-7 sm:px-7">
    <header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Administrator workspace</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-950">Govern the civic resolution system</h1><p className="mt-2 max-w-3xl text-slate-600">Manage access and the operational catalog. These controls are protected server-side and are never exposed to citizen accounts.</p></div><Button variant="outline" disabled={seedDemo.isPending} onClick={async () => { try { const result = await seedDemo.mutateAsync(); await refresh(); toast.success(result.message); } catch { toast.error("Demo data could not be prepared."); } }}><DatabaseZap className="mr-2 h-4 w-4" />Prepare demo data</Button></header>
    <p className="mt-3 rounded-xl bg-amber-50 px-3 py-2 text-xs text-amber-900">Demo data is clearly labeled and kept separate from citizen-created records. It does not create login credentials; use the protected access controls below for signed-in team members.</p>
    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total reports" value={analytics.data?.total ?? 0} /><Metric label="High / critical" value={(analytics.data?.byPriority.HIGH ?? 0) + (analytics.data?.byPriority.CRITICAL ?? 0)} /><Metric label="Resolved" value={analytics.data?.byStatus.RESOLVED ?? 0} /><Metric label="Avg. resolution" value={analytics.data?.averageResolutionHours === null || analytics.data?.averageResolutionHours === undefined ? "—" : `${analytics.data.averageResolutionHours} h`} /></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-sky-50 text-sky-700"><UsersRound className="h-5 w-5" /></span><div><h2 className="font-black">User access</h2><p className="text-sm text-slate-600">Assign civic roles and departmental scope.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Account</th><th className="px-5 py-3">Role</th><th className="px-5 py-3">Department</th><th className="px-5 py-3" /></tr></thead><tbody>{users.data?.map(item => <UserRow key={item.id} user={item} departments={departments.data ?? []} saving={updateUser.isPending} onSave={saveUser} />)}{!users.isLoading && !users.data?.length && <tr><td colSpan={4} className="px-5 py-10 text-center text-slate-500">No user accounts are available yet.</td></tr>}</tbody></table></div></section>
      <div className="space-y-6">
        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Building2 className="h-5 w-5" /></span><div><h2 className="font-black">Departments</h2><p className="text-sm text-slate-600">Route complaints to active service teams.</p></div></div><form className="mt-4 space-y-2" onSubmit={async event => { event.preventDefault(); if (!departmentName.trim()) return; try { await createDepartment.mutateAsync({ name: departmentName.trim(), description: departmentDescription.trim() || null }); setDepartmentName(""); setDepartmentDescription(""); await refresh(); toast.success("Department created."); } catch { toast.error("Department could not be created. Ensure its name is unique."); } }}><Input value={departmentName} onChange={event => setDepartmentName(event.target.value)} placeholder="Department name" maxLength={120} /><Textarea value={departmentDescription} onChange={event => setDepartmentDescription(event.target.value)} placeholder="Short description (optional)" className="min-h-16" maxLength={1000} /><Button type="submit" size="sm" disabled={createDepartment.isPending}><Plus className="mr-1.5 h-4 w-4" />Add department</Button></form><div className="mt-5 divide-y divide-slate-100">{departments.data?.map(item => <div key={item.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-bold">{item.name}</p><p className="text-xs text-slate-500">{item.active ? "Active in routing" : "Inactive"}</p></div><button disabled={setDepartmentActive.isPending} onClick={async () => { try { await setDepartmentActive.mutateAsync({ id: item.id, active: !item.active }); await refresh(); toast.success(`Department ${item.active ? "deactivated" : "activated"}.`); } catch { toast.error("Department status could not be updated."); } }} className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.active ? "bg-emerald-50 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{item.active ? "Active" : "Inactive"}</button></div>)}</div></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-50 text-violet-700"><BarChart3 className="h-5 w-5" /></span><div><h2 className="font-black">Issue categories</h2><p className="text-sm text-slate-600">Maintain the citizen reporting taxonomy.</p></div></div><form className="mt-4 flex gap-2" onSubmit={async event => { event.preventDefault(); if (!categoryName.trim()) return; try { await createCategory.mutateAsync({ name: categoryName.trim(), departmentId: categoryDepartment ? Number(categoryDepartment) : null }); setCategoryName(""); await refresh(); toast.success("Category created."); } catch { toast.error("Category could not be created. Ensure its name is unique."); } }}><Input value={categoryName} onChange={event => setCategoryName(event.target.value)} placeholder="Category name" maxLength={120} /><select value={categoryDepartment} onChange={event => setCategoryDepartment(event.target.value)} className="max-w-40 rounded-lg border border-slate-200 bg-white px-2 text-sm"><option value="">No department</option>{departments.data?.filter(item => item.active).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Button type="submit" size="icon" aria-label="Add category" disabled={createCategory.isPending}><Plus className="h-4 w-4" /></Button></form><div className="mt-5 divide-y divide-slate-100">{categories.data?.map(item => <div key={item.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-bold">{item.name}</p><p className="text-xs text-slate-500">{item.active ? "Available to citizens" : "Hidden from reporting"}</p></div><button disabled={setCategoryActive.isPending} onClick={async () => { try { await setCategoryActive.mutateAsync({ id: item.id, active: !item.active }); await refresh(); toast.success(`Category ${item.active ? "deactivated" : "activated"}.`); } catch { toast.error("Category status could not be updated."); } }} className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.active ? "bg-violet-50 text-violet-800" : "bg-slate-100 text-slate-600"}`}>{item.active ? "Active" : "Inactive"}</button></div>)}</div></section>
      </div>
    </section>
  </main></AuthorityLayout>;
}

function Metric({ label, value }: { label: string; value: number | string }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 text-3xl font-black tracking-tight text-slate-950">{value}</p></section>; }
function UserRow({ user, departments, saving, onSave }: { user: AdminUser; departments: Department[]; saving: boolean; onSave: (id: number, role: Role, departmentId: string) => Promise<void> }) { const [role, setRole] = useState(user.role); const [departmentId, setDepartmentId] = useState(user.departmentId ? String(user.departmentId) : ""); return <tr className="border-b border-slate-100 last:border-0"><td className="px-5 py-4"><p className="font-bold text-slate-950">{user.name ?? "Unnamed user"}</p><p className="text-xs text-slate-500">{user.email ?? "No email"}</p></td><td className="px-5 py-4"><select value={role} onChange={event => setRole(event.target.value as Role)} className="rounded-lg border border-slate-200 bg-white px-2 py-1.5 text-sm"><option value="citizen">Citizen</option><option value="authority">Authority</option><option value="admin">Admin</option></select></td><td className="px-5 py-4"><select disabled={role !== "authority"} value={departmentId} onChange={event => setDepartmentId(event.target.value)} className="rounded-lg border border-slate-200 bg-white px-2 py-1.5 text-sm disabled:bg-slate-50"><option value="">No department</option>{departments.filter(item => item.active).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></td><td className="px-5 py-4 text-right"><Button size="sm" variant="outline" disabled={saving} onClick={() => onSave(user.id, role, departmentId)}>Save</Button></td></tr>; }
