import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { ArrowRight, ClipboardCheck, MapPinned, ShieldCheck, Sparkles, Workflow } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "wouter";

export default function Landing() {
  const { user, loading } = useAuth();
  const destination = user?.role === "citizen" ? "/citizen" : "/authority";
  return <main className="min-h-screen overflow-hidden bg-[#f7f9f8] text-slate-950">
    <header className="mx-auto flex h-20 max-w-6xl items-center justify-between px-5 sm:px-6"><Link href="/" className="flex items-center gap-2.5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-700 text-white shadow-lg shadow-emerald-950/10"><ShieldCheck className="h-5 w-5" /></span><span className="text-xl font-extrabold tracking-tight">CIVIC<span className="text-emerald-700">FLOW</span></span></Link><div className="flex items-center gap-2">{!loading && (user ? <Link href={destination}><Button className="bg-slate-950 hover:bg-slate-800">Open workspace <ArrowRight className="ml-2 h-4 w-4" /></Button></Link> : <Button variant="outline" onClick={() => startLogin()}>Sign in</Button>)}<Link href="/demo-login"><Button variant="outline" className="border-emerald-200 text-emerald-800 hover:bg-emerald-50">Try demo</Button></Link></div></header>
    <section className="relative mx-auto grid max-w-6xl gap-12 px-5 pb-20 pt-12 sm:px-6 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:pb-28 lg:pt-20"><div className="absolute -left-40 top-0 -z-0 h-96 w-96 rounded-full bg-emerald-200/35 blur-3xl" /><div className="relative z-10"><div className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white px-3 py-1.5 text-xs font-bold text-emerald-800 shadow-sm"><Sparkles className="h-3.5 w-3.5" /> A clearer path from issue to action</div><h1 className="mt-6 max-w-2xl text-5xl font-extrabold leading-[1.04] tracking-[-0.045em] sm:text-6xl">Local problems, <span className="text-emerald-700">made visible.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">CIVICFLOW gives people one simple way to report civic issues — and gives responsible teams a practical workflow to prioritize, resolve, and communicate progress.</p><div className="mt-8 flex flex-wrap gap-3">{user ? <Link href={destination}><Button size="lg" className="bg-emerald-700 hover:bg-emerald-800">Open your workspace <ArrowRight className="ml-2 h-4 w-4" /></Button></Link> : <Button size="lg" className="bg-emerald-700 hover:bg-emerald-800" onClick={() => startLogin()}>Report a problem <ArrowRight className="ml-2 h-4 w-4" /></Button>}<Link href="/demo-login"><Button size="lg" variant="outline">Use test demo</Button></Link><a href="#how-it-works"><Button size="lg" variant="outline">See how it works</Button></a></div></div><div className="relative z-10"><div className="rounded-[2rem] border border-white bg-white p-5 shadow-2xl shadow-slate-900/10 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-500">Live civic workflow</p><h2 className="mt-1 text-xl font-bold">Report CF-8KD42M1P</h2></div><span className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-800">In progress</span></div><div className="mt-6 overflow-hidden rounded-2xl bg-[linear-gradient(135deg,#e2e8f0,#cbd5e1)] p-5"><div className="mx-auto h-36 max-w-xs rounded-xl bg-slate-700 shadow-xl"><div className="mx-auto mt-4 h-3 w-24 rounded-full bg-slate-600" /><div className="mx-auto mt-8 h-8 w-36 rounded-full border-4 border-slate-900 bg-slate-800" /></div></div><div className="mt-6 space-y-4">{[["1","Submitted","Your report and location are securely recorded."],["2","Verified","The appropriate team reviews the issue."],["3","In progress","Work updates appear in your timeline."]].map(([number, title, copy], index) => <div key={title} className="flex gap-3"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full text-xs font-bold ${index < 2 ? "bg-emerald-700 text-white" : "bg-blue-600 text-white"}`}>{number}</span><div><p className="text-sm font-bold">{title}</p><p className="text-xs leading-5 text-slate-500">{copy}</p></div></div>)}</div></div></div></section>
    <section id="how-it-works" className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-16 sm:px-6 md:grid-cols-3">{[[MapPinned,"Pin the exact place","Add a photo, description, and confirmed map location in a few steps."],[Sparkles,"Organize intelligently","AI recommendations help teams classify and prioritize without replacing their judgement."],[Workflow,"Track real action","Follow verified workflow updates from submission through resolution."]].map(([Icon, title, copy]) => { const ActualIcon = Icon as typeof MapPinned; return <article key={title as string} className="rounded-2xl border border-slate-100 p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><ActualIcon className="h-5 w-5" /></span><h2 className="mt-5 text-lg font-bold">{title as string}</h2><p className="mt-2 leading-6 text-slate-600">{copy as string}</p></article>})}</div></section>
    <footer className="mx-auto flex max-w-6xl items-center justify-between px-5 py-8 text-sm text-slate-500 sm:px-6"><span>Built for transparent civic action.</span><span className="flex items-center gap-2"><ClipboardCheck className="h-4 w-4 text-emerald-700" /> Report once. Follow every step.</span></footer>
  </main>;
}
